export interface ThemeDefinition {
	id: string;
	name: string;
	description: string;
	unlockHint: string;
	duration: number | "permanent" | "toggle";
	isExclusive: boolean;
	cssOverrides?: Record<string, string>;
	fontFamily?: string;
	bodyClass: string;
	triggerType: "type" | "click" | "rank";
	triggerValue: string;
}

export const THEMES: ThemeDefinition[] = [
	{
		id: "vaporwave",
		name: "VAPORWAVE",
		description: "Aesthetic digital dreams of the 80s.",
		unlockHint: "Something about the way things look...",
		duration: "toggle",
		isExclusive: false,
		bodyClass: "theme-vaporwave",
		triggerType: "type",
		triggerValue: "aesthetic",
		fontFamily: "'Orbitron', sans-serif",
	},
	{
		id: "terminal",
		name: "TERMINAL",
		description: "Access granted. System override active.",
		unlockHint: "Superuser powers required.",
		duration: 60,
		isExclusive: false,
		bodyClass: "theme-terminal",
		triggerType: "type",
		triggerValue: "sudo",
		fontFamily: "'Share Tech Mono', monospace",
	},
	{
		id: "blueprint",
		name: "BLUEPRINT",
		description: "The architectural framework of the club.",
		unlockHint: "Inspect your dedication to the lab.",
		duration: "toggle",
		isExclusive: false,
		bodyClass: "theme-blueprint",
		triggerType: "type",
		triggerValue: "technologia",
		fontFamily: "'Share Tech Mono', monospace",
	},
	{
		id: "newspaper",
		name: "NEWSPAPER",
		description: "EXTRA EXTRA! Read all about it!",
		unlockHint: "Reporting the latest news.",
		duration: 120,
		isExclusive: false,
		bodyClass: "theme-newspaper",
		triggerType: "type",
		triggerValue: "extra extra",
		fontFamily: "'Playfair Display', serif",
	},
	{
		id: "deepsea",
		name: "DEEP SEA",
		description: "Bioluminescent wonder in the digital abyss.",
		unlockHint: "Touch your identity, then the club's heart.",
		duration: "toggle",
		isExclusive: false,
		bodyClass: "theme-deepsea",
		triggerType: "type",
		triggerValue: "tentacles",
	},
	{
		id: "coffeeshop",
		name: "COFFEE SHOP",
		description: "Warm brews and coding fuel.",
		unlockHint: "Just... one... more...",
		duration: "toggle",
		isExclusive: false,
		bodyClass: "theme-coffeeshop",
		triggerType: "type",
		triggerValue: "one more cup",
		fontFamily: "'Caveat', cursive",
	},
	{
		id: "redacted",
		name: "REDACTED",
		description: "[CLASSIFIED DOCUMENT] - Level 4 Clearance.",
		unlockHint: "Pester the members repeatedly.",
		duration: 180,
		isExclusive: false,
		bodyClass: "theme-redacted",
		triggerType: "type",
		triggerValue: "epstein",
		fontFamily: "'Courier Prime', monospace",
	},
	{
		id: "windows95",
		name: "WINDOWS 95",
		description: "Where do you want to go today?",
		unlockHint: "It looks like you're trying to unlock a theme.",
		duration: "toggle",
		isExclusive: false,
		bodyClass: "theme-windows95",
		triggerType: "type",
		triggerValue: "clippy",
	},
	{
		id: "matrix",
		name: "MATRIX",
		description: "You take the red pill, you stay in Wonderland.",
		unlockHint: "Follow the white rabbit.",
		duration: 60,
		isExclusive: false,
		bodyClass: "theme-matrix",
		triggerType: "type",
		triggerValue: "follow the white rabbit",
		fontFamily: "'Share Tech Mono', monospace",
	},
	{
		id: "gold",
		name: "GOLD",
		description: "The mark of true robotics mastery.",
		unlockHint: "Reach the pinnacle of the cursus.",
		duration: "permanent",
		isExclusive: true,
		bodyClass: "theme-gold",
		triggerType: "rank",
		triggerValue: "S",
	},
	{
		id: "crayola",
		name: "CRAYOLA",
		description: "Stay inside the lines (if you can).",
		unlockHint: "Poke the binary robot until it breaks.",
		duration: "toggle",
		isExclusive: false,
		bodyClass: "theme-crayola",
		triggerType: "type",
		triggerValue: "crayons are yummy",
		fontFamily: "'Caveat', cursive",
	},
	{
		id: "synthwave",
		name: "SYNTHWAVE",
		description: "Outrun the sunset on the neon grid.",
		unlockHint: "Outrun the future.",
		duration: "toggle",
		isExclusive: false,
		bodyClass: "theme-synthwave",
		triggerType: "type",
		triggerValue: "outrun",
		fontFamily: "'Orbitron', sans-serif",
	},
	{
		id: "highcontrast",
		name: "HIGH CONTRAST",
		description: "Maximum clarity, zero noise.",
		unlockHint: "Seek total clarity.",
		duration: "toggle",
		isExclusive: false,
		bodyClass: "theme-highcontrast",
		triggerType: "type",
		triggerValue: "clarity",
	},
	{
		id: "godmode",
		name: "GODMODE",
		description: "Everything is fine. Definitely fine.",
		unlockHint: "Ascend to divinity.",
		duration: "toggle",
		isExclusive: false,
		bodyClass: "theme-godmode",
		triggerType: "type",
		triggerValue: "godmode",
	},
	{
		id: "retro",
		name: "RETRO",
		description: "RC_SYSTEMS_OVERRIDE: Legacy mainframe active.",
		unlockHint: "Up, Up, Down, Down...",
		duration: "toggle",
		isExclusive: false,
		bodyClass: "theme-retro",
		triggerType: "type",
		triggerValue: "konami",
		fontFamily: "'Share Tech Mono', monospace",
	},
];

export const getThemeById = (id: string) => THEMES.find((t) => t.id === id);
